---
profile: cachyos-niri
pkg_manager: pacman
aur_helper: paru

extra_packages:
  - evince
  - gnome-text-editor
  - niri
  - wtype
  - cliphist
  # build deps para PHP via mise
  - base-devel
  - re2c
  - libxml2
  - libpng
  - libjpeg-turbo
  - libzip
  - oniguruma
  - sqlite
  - gd
  - libedit
  - icu
  - mariadb-libs
  - postgresql-libs
  - readline
  - openssl
  - pkgconf

aur_packages:
  - slack-desktop
  - freelens-bin
  - gearlever
  - 1password
  - distroshelf
  - input-remapper-bin
  - trezor-suite-bin
  - trezor-udev
  - sparrow-wallet
gamepad_packages:
  - xpadneo-dkms
